# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e08ddca204af848d88da311d21c60d714b7b348455bc473f0ed3f0c780639cdcf0922f1ebbdef9c31a4e59951ea64010a8554675aac7575b1d1a948c03c8534

test:
  secret_key_base: a88f33b6588297c0556e93e96f972b9aa6476623ceaf33fa49c6b31ece9a5667b17d20c2190df826a880b3ba7e053bdbbd03fbdb6c8e71af95ec33b5a53cd10e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
